# Generated by Django 3.1.1 on 2020-10-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecasthour',
            name='uv',
        ),
    ]
