# Generated by Django 3.1.1 on 2020-10-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_remove_forecasthour_uv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecasthour',
            old_name='daily_chance_of_rain',
            new_name='chance_of_rain',
        ),
        migrations.RenameField(
            model_name='forecasthour',
            old_name='daily_chance_of_snow',
            new_name='chance_of_snow',
        ),
        migrations.RenameField(
            model_name='forecasthour',
            old_name='daily_will_it_rain',
            new_name='will_it_rain',
        ),
        migrations.RenameField(
            model_name='forecasthour',
            old_name='daily_will_it_snow',
            new_name='will_it_snow',
        ),
    ]
