# Generated by Django 3.1.1 on 2020-09-19 08:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
