# Generated by Django 3.1.1 on 2020-10-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_city_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='time_zone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
